name: ciphercopy_cli
description: Command-line interface for CiPHERCOPY: multi-threaded batch file copy, SHA-1 manifest generation & verification, progress bars, logging, and cancellation.
version: 1.0.0
repository: https://github.com/thursby/ciphercopy

environment:
  sdk: ^3.9.0

dependencies:
  
  path: ^1.9.0
  crypto: ^3.0.6
  ansicolor: ^2.0.1
  args: ^2.4.2
  logging: ^1.3.0
  console_bars: ^1.2.1

  ciphercopy_core:
    path: ../core/

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
