publish_to: 'none'
name: ciphercopy_core
description: "Core engine for CiPHERCOPY: high-performance multi-threaded file copy, SHA-1 manifest generation & verification, progress events, and cooperative cancellation."
version: 1.0.0
repository: https://github.com/thursby/ciphercopy

environment:
  sdk: ^3.9.0

dependencies:
  crypto: ^3.0.6
  logging: ^1.3.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
