name: ciphercopy
description: "Flutter GUI for CiPHERCOPY: multi-threaded file copy & SHA-1 verification with live progress, logs, and cancellation."
publish_to: 'none'
version: 0.1.0
repository: https://github.com/thursby/ciphercopy

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  file_selector: ^1.0.3
  file_selector_macos: ^0.9.4+4
  window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  ciphercopy_core:
    path: ../core/

flutter:
  uses-material-design: true
