name: ciphercopy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  file_selector: ^1.0.3
  file_selector_macos: ^0.9.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  ciphercopy_core:
    path: ../core/

flutter:
  uses-material-design: true
